# The name of the mod loader type to load - for regular FML @Mod mods it should be javafml
modLoader="javafml" #mandatory

# A version range to match for said mod loader - for regular FML @Mod it will be the forge version
loaderVersion="[35,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.

# The license for you mod. This is mandatory metadata and allows for easier comprehension of your redistributive properties.
# Review your options at https://choosealicense.com/. All rights reserved is the default copyright stance, and is thus the default here.
license="All rights reserved"

# A URL to refer people to when problems occur with this mod
issueTrackerURL="https://github.com/ace10102/ArcaneFundamentals" #optional

# A list of mods - how many allowed here is determined by the individual mod loader
[[mods]] #mandatory

# The modid of the mod
modId="arcanefundamentals" #mandatory

# The version number of the mod - there's a few well known ${} variables useable here or just hardcode it
# ${file.jarVersion} will substitute the value of the Implementation-Version as read from the mod's JAR file metadata
# see the associated build.gradle script for how to populate this completely automatically during a build
version="${file.jarVersion}" #mandatory

 # A display name for the mod
displayName="Arcane Fundamentals" #mandatory

# A URL to query for updates for this mod. See the JSON update specification https://mcforge.readthedocs.io/en/latest/gettingstarted/autoupdate/
#updateJSONURL="https://change.me.example.invalid/updates.json" #optional

# A URL for the "homepage" for this mod, displayed in the mod UI
#displayURL="https://change.me.to.your.mods.homepage.example.invalid/" #optional

# A file name (in the root of the mod JAR) containing a logo for display
#logoFile="examplemod.png" #optional

# A text field displayed in the mod UI
credits="Hallzmine for mana-plus which this mod took over, and of course Mithion for making Mana & Artifice for which this is an addon." #optional

# A text field displayed in the mod UI
authors="Hallzmine, Spoilers," #optional

# The description text for the mod (multi line!) (#mandatory)
description='''
An addon for Mana&Artifice which adds some basic features to make the mod a bit more forgiving.
'''

# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
[[dependencies.arcanefundamentals]] #optional
    # the modid of the dependency
    modId="forge" #mandatory
    # Does this dependency have to exist - if not, ordering below must be specified
    mandatory=true #mandatory
    # The version range of the dependency
    versionRange="[35,)" #mandatory
    # An ordering relationship for the dependency - BEFORE or AFTER required if the relationship is not mandatory
    ordering="NONE"
    # Side this dependency is applied on - BOTH, CLIENT or SERVER
    side="BOTH"
    
# Here's another dependency
[[dependencies.arcanefundamentals]]
    modId="minecraft"
    mandatory=true
# This version range declares a minimum of the current minecraft version up to but not including the next major version
    versionRange="[1.16,1.17)"
    ordering="NONE"
    side="BOTH"

[[dependencies.arcanefundamentals]]
	modId="mana-and-artifice"
	mandatory=true
	versionRange="[1.3.0.0,)"
	ordering="NONE"
	side="BOTH"
	